log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blocks-sync-svc
  service_port: 80

contract:
  node: "wss://base-mainnet.infura.io/ws/v3/c2d071d5962546958be340501a4c13e7"
  private_key: "69d9f3abacb8ae009390376e5a51352403ab651a34936a71dafdac30a72196cc" 
  address: "1DD10c5FfaDbF14E746d154aF1a9df806AAE4159"
  batch_size: 100
  interval: 60 # 1 time per hour

rpc:
  url: "http://192.168.1.59:8332"
  user: "bitcoin"
  password: "ilovebitcoin"