pub global CURRENT_TX_SIZE: u32 = 302;
pub global PREV_TX_SIZE: u32 = 468;
pub global UTXOS_SIZE: u32 = 43;
pub global SIGNATURE_SIZE: u32 = 65;

pub global CURRENT_TX_IN_COUNT: u32 = 1;
pub global CURRENT_TX_IN_COUNT_SIZE: u32 = 1;
pub global CURRENT_TX_IN_SIZE: u32 = 42;
pub global CURRENT_TX_OUT_COUNT: u32 = 1;
pub global CURRENT_TX_OUT_COUNT_SIZE: u32 = 1;
pub global CURRENT_TX_OUT_SIZE: u32 = 32;
pub global CURRENT_TX_MAX_WITNESS_STACK_SIZE: u32 = 1;
pub global CURRENT_TX_WITNESS_SIZE: u32 = 67;
pub global IS_CURRENT_SEGWIT: bool = true;

pub global PREV_TX_IN_COUNT: u32 = 1;
pub global PREV_TX_IN_COUNT_SIZE: u32 = 1;
pub global PREV_TX_IN_SIZE: u32 = 42;
pub global PREV_TX_OUT_COUNT: u32 = 2;
pub global PREV_TX_OUT_COUNT_SIZE: u32 = 1;
pub global PREV_TX_OUT_SIZE: u32 = 75;
pub global PREV_TX_MAX_WITNESS_STACK_SIZE: u32 = 2;
pub global PREV_TX_WITNESS_SIZE: u32 = 107;
pub global IS_PREV_SEGWIT: bool = true;

pub global N_OUTPUT_SIZE: u32 = 31;
