pub global CURRENT_TX_SIZE: u32 = 170;
pub global PREV_TX_SIZE: u32 = 522;
pub global SCRIPT_SIG_SIZE: u32 = 294;
pub global SCRIPT_PUB_KEY_SIZE: u32 = 201;
pub global SCRIPT_PUB_KEY_SIZE_SIZE: u32 = 1;

pub global CURRENT_TX_IN_COUNT: u32 = 1;
pub global CURRENT_TX_IN_COUNT_SIZE: u32 = 1;
pub global CURRENT_TX_IN_SIZE: u32 = 42;
pub global CURRENT_TX_OUT_COUNT: u32 = 1;
pub global CURRENT_TX_OUT_COUNT_SIZE: u32 = 1;
pub global CURRENT_TX_OUT_SIZE: u32 = 35;

pub global PREV_TX_IN_COUNT: u32 = 1;
pub global PREV_TX_IN_COUNT_SIZE: u32 = 1;
pub global PREV_TX_IN_SIZE: u32 = 42;
pub global PREV_TX_OUT_COUNT: u32 = 1;
pub global PREV_TX_OUT_COUNT_SIZE: u32 = 1;
pub global PREV_TX_OUT_SIZE: u32 = 211;
pub global PREV_TX_MAX_WITNESS_STACK_SIZE: u32 = 0;
pub global PREV_TX_WITNESS_SIZE: u32 = 0;
pub global IS_PREV_SEGWIT: bool = false;

pub global OPCODES_COUNT: u32 = 9;
pub global STACK_SIZE: u32 = 11;
pub global MAX_STACK_ELEMENT_SIZE: u32 = 72;
pub global N_OUTPUT_SIZE: u32 = 34;
pub global INPUT_TO_SIGN: u32 = 0;
pub global INPUT_TO_SIGN_SIZE: u32 = 1;
pub global N_INPUT_SIZE: u32 = 41;
